name: run tests
on: 
  push:
    branches: '!main'
jobs:
  build-and-deploy-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.x'
      - name: Run Tests
        run: dotnet test ./src